#ifndef MOONLANDER_H
#define MOONLANDER_H

void MoonLander_SpaceshipInit();
void MoonLander_phsics(double dt);
void setX(double n);
void setDX(double n);
void setDDX(double n);
void setY(double n);
void setDY(double n);
void setDDY(double n);
void setZ(double n);
void setDZ(double n);
void setDDZ(double n);
void setRoll(double n);
void setDRoll(double n);
void setDDRoll(double n);
void setYaw(double n);
void setDYaw(double n);
void setDDYaw(double n);
void setPitch(double n);
void setDPitch(double n);
void setDDPitch(double n);
double getX();
double getDX();
double getDDX();
double getY();
double getDY();
double getDDY();
double getZ();
double getDZ();
double getDDZ();
double getRoll();
double getDRoll();
double getDDRoll();
double getYaw();
double getDYaw();
double getDDYaw();
double getPitch();
double getDPitch();
double getDDPitch();
void addX(double n);
void addDX(double n);
void addDDX(double n);
void addY(double n);
void addDY(double n);
void addDDY(double n);
void addZ(double n);
void addDZ(double n);
void addDDZ(double n);
void addRoll(double n);
void addDRoll(double n);
void addDDRoll(double n);
void addYaw(double n);
void addDYaw(double n);
void addDDYaw(double n);
void addPitch(double n);
void addDPitch(double n);
void addDDPitch(double n);
void ThrustDDX(double n);
void ThrustDDY(double n);
void ThrustDDZ(double n);
void ThrustDDRoll(double n);
void ThrustDDYaw(double n);
void ThrustDDPitch(double n);
void thrusterLoop();
void manual();
int getKey();
void setManual();
int isManual();
int landed();
void end();
char* getPilotMSG();
void pilotInit();

#endif